#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

# SSC335 Tapo C310
if [ "$1" = "rtl8192eu-ssc335-tapo-c310" ]; then
    set_gpio 16 1
	modprobe 8192eu
	exit 0
fi

exit 1
